export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  // 业务错误码 —— service/store 抛出，controller/页面分别包装展示
  ASSET_NOT_FOUND: "ASSET_NOT_FOUND",
  FAULT_NOT_FOUND: "FAULT_NOT_FOUND",
  FAULT_ALREADY_TICKETED: "FAULT_ALREADY_TICKETED",
  FAULT_MERGE_SELF: "FAULT_MERGE_SELF",
  FAULT_MERGE_TARGET_MERGED: "FAULT_MERGE_TARGET_MERGED",
  FAULT_MERGE_DIFFERENT_LINE: "FAULT_MERGE_DIFFERENT_LINE",
  TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
  TICKET_STATUS_ILLEGAL: "TICKET_STATUS_ILLEGAL",
  CREW_NOT_DISPATCHABLE: "CREW_NOT_DISPATCHABLE",
  CREW_SKILL_MISMATCH: "CREW_SKILL_MISMATCH",
  PART_NOT_FOUND: "PART_NOT_FOUND",
  PART_STOCK_INSUFFICIENT: "PART_STOCK_INSUFFICIENT",
  PART_REQ_NOT_PENDING: "PART_REQ_NOT_PENDING",
  PART_REQ_NOT_APPROVED: "PART_REQ_NOT_APPROVED"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
