export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  NOT_FOUND: "NOT_FOUND",
  INVALID_TRANSITION: "INVALID_TRANSITION",
  DUPLICATE_MERGE: "DUPLICATE_MERGE",
  NO_AVAILABLE_CREW: "NO_AVAILABLE_CREW",
  PART_PENDING_APPROVAL: "PART_PENDING_APPROVAL",
  PART_INSUFFICIENT_STOCK: "PART_INSUFFICIENT_STOCK",
  PART_ALREADY_DECIDED: "PART_ALREADY_DECIDED",
  ASSET_NOT_FOUND: "ASSET_NOT_FOUND",
  TICKET_NOT_ACTIVE: "TICKET_NOT_ACTIVE",
  UNKNOWN_ACTION: "UNKNOWN_ACTION"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
